// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace empManagementDapper
{
    public partial class Dependent
    {
        public int DependentId { get; set; }
        public int EmpId { get; set; }
        public string Relation { get; set; }
        public DateTime? DepDob { get; set; }

        public virtual Employee Emp { get; set; }
    }
}