// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace empManagementDapper
{
    public partial class Emplevel
    {
        public int LevelNo { get; set; }
        public int? LowSalary { get; set; }
        public int? HighSalary { get; set; }
    }
}