// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Department = new HashSet<Department>();
            Dependent = new HashSet<Dependent>();
        }

        [Key]
        public int EmpId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string EmpFname { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string EmpLname { get; set; }
        public int? DeptId { get; set; }
        public int? QualId { get; set; }
        public int? PositionId { get; set; }
        public int? Supervisor { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Hiredate { get; set; }
        public int? Salary { get; set; }
        public int? Commission { get; set; }

        [ForeignKey("DeptId")]
        [InverseProperty("Employee")]
        public virtual Department Dept { get; set; }
        [ForeignKey("PositionId")]
        [InverseProperty("Employee")]
        public virtual Position Position { get; set; }
        [ForeignKey("QualId")]
        [InverseProperty("Employee")]
        public virtual Qualification Qual { get; set; }
        [InverseProperty("ManagerNavigation")]
        public virtual ICollection<Department> Department { get; set; }
        [InverseProperty("Emp")]
        public virtual ICollection<Dependent> Dependent { get; set; }
    }
}