// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeManagement
{
    public partial class Qualification
    {
        public Qualification()
        {
            Employee = new HashSet<Employee>();
        }

        public int QualId { get; set; }
        public string QualDesc { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
    }
}