// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Models
{
    public partial class Dependent
    {
        [Key]
        public int DependentId { get; set; }
        public int EmpId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Relation { get; set; }
        [Column("DepDOB", TypeName = "date")]
        public DateTime? DepDob { get; set; }

        [ForeignKey("EmpId")]
        [InverseProperty("Dependent")]
        public virtual Employee Emp { get; set; }
    }
}